name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  Windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update submodules
      run: git submodule update --init

    - name: Build
      run: ${{github.workspace}}\scripts\build.bat ${{env.BUILD_TYPE}}

    - name: Run unit tests
      run: ${{github.workspace}}\build\test\${{env.BUILD_TYPE}}\ComlintCppTests.exe

    - name: Run smoke tests
      run: ${{github.workspace}}\scripts\smoke_tests.bat

  Linux-build:
    runs-on: linux-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update submodules
      run: git submodule update --init

    - name: Build
      run: ${{github.workspace}}/scripts/build.sh ${{env.BUILD_TYPE}}

    - name: Run unit tests for ComlintCpp
      run: ${{github.workspace}}/build/bin/ComlintCppTests
    
    - name: Run smoke tests
      run: ${{github.workspace}}/scripts/smoke_tests.sh