name: Windows release build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  Build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update submodules
      run: git submodule update --init

    - name: Build
      run: ${{github.workspace}}\scripts\build.bat ${{env.BUILD_TYPE}}

    - name: Run unit tests
      run: ${{github.workspace}}\build\test\${{env.BUILD_TYPE}}\ComlintCppTests.exe

    - name: Run smoke tests
      run: ${{github.workspace}}\scripts\smoke_tests.bat ${{env.BUILD_TYPE}}

  Test:
    runs-on: windows-latest

    steps:
    - name: Run unit tests
      run: ${{github.workspace}}\build\test\${{env.BUILD_TYPE}}\ComlintCppTests.exe

    - name: Run smoke tests
      run: ${{github.workspace}}\scripts\smoke_tests.bat ${{env.BUILD_TYPE}}